### ISSUE TITLE
这个项目是干啥的

### ISSUE THREAD

**Issue by TTHHR** [dxkite/meow-web#1]
http转发，nginx?

**Comment by dxkite** [comment]
毫无疑问，他定位应该算是一个轮子，设计上主要功能作为一个带鉴权以及守护进程的HTTP网关来使用，主要出于一下考虑：
 
不同人开发了不同的项目、不同的语言的接口，通过这个项目可以把他们整合到一起
- 守护进程 - 负责启动不同的项目
- HTTP网关 - 提供不同项目的统一鉴权

可以理解为一个微服务网关？
